// Copyright ©️ 2026 Sebastian Delmont <sd@ham2k.com>
// SPDX-License-Identifier: MIT
//
// ARRL and RAC sections — the exchange ARRL Field Day asks for.
//
// DUPLICATED, on purpose. `wfd` carries its own copy of this file and of
// the scorer beside it. The two contests are near-identical and a factory would
// express that, but each extension is meant to stand alone — to be read, moved
// and distributed without reaching into a sibling — and that is worth more here
// than not repeating the table. app-polo's `wfd` imports app-polo's `fd` for
// exactly this data; the copy is the deliberate divergence.
//
// INLINE DATA. A scorer is synchronous and a host call is not
// (docs/design/contests.md §5.3), so a section table living behind
// `dbLookupSelectAll` could not be read while folding a log.
//
// PROVENANCE, stated exactly: the data is app-polo's, transformed mechanically
// rather than retyped, and every entry was checked back against that source. It
// has NOT been checked against the ARRL's own published list — an earlier
// version of this comment claimed it had, which was wrong and is the sort of
// claim that stops the next reader looking.
//
// One correction against app-polo, on Sebastian's reading of the rules: it
// lists `YT` as a RAC section, which RAC has indeed added — but FIELD DAY still
// counts Yukon inside `TER`, so YT is not a valid exchange here and is not
// listed. 14 RAC sections, not 15.

/// The 71 ARRL sections, code to full name.
export const ARRL_SECTIONS: Record<string, string> = {
  AK: "Alaska",
  AL: "Alabama",
  AR: "Arkansas",
  AZ: "Arizona",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  EB: "East Bay",
  EMA: "Eastern Massachusetts",
  ENY: "Eastern New York",
  EPA: "Eastern Pennsylvania",
  EWA: "Eastern Washington",
  GA: "Georgia",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  LAX: "Los Angeles",
  MDC: "Maryland & DC",
  ME: "Maine",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NFL: "Northern Florida",
  NH: "New Hampshire",
  NLI: "New York City & Long Island",
  NM: "New Mexico",
  NNJ: "Northern New Jersey",
  NNY: "Northern New York",
  NTX: "North Texas",
  NV: "Nevada",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  ORG: "Orange",
  PAC: "Pacific",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SB: "Santa Barbara",
  SC: "South Carolina",
  SCV: "Santa Clara Valley",
  SD: "South Dakota",
  SDG: "San Diego",
  SF: "San Francisco",
  SFL: "Southern Florida",
  SJV: "San Joaquin Valley",
  SNJ: "Southern New Jersey",
  STX: "South Texas",
  SV: "Sacramento Valley",
  TN: "Tennessee",
  UT: "Utah",
  VA: "Virginia",
  VI: "US Virgin Islands",
  VT: "Vermont",
  WCF: "West Central Florida",
  WI: "Wisconsin",
  WMA: "Western Massachusetts",
  WNY: "Western New York",
  WPA: "Western Pennsylvania",
  WTX: "West Texas",
  WV: "West Virginia",
  WWA: "Western Washington",
  WY: "Wyoming",
}

/// The 14 RAC sections Field Day uses, tallied separately from ARRL's — as are
/// `MX` and `DX`.
///
/// RAC has since made Yukon (`YT`) a section of its own, but FIELD DAY still
/// counts it inside `TER`, so a Yukon station sends TER here and `YT` is not a
/// valid exchange. app-polo lists YT and is wrong for this purpose; the rest of
/// this file always agreed with Field Day — `PREFIX_TO_LOCATION` maps VY1 to
/// `TER`, and neither the abbreviation nor the call-area table ever had a YT
/// row — so removing it is what makes the file self-consistent.
export const RAC_SECTIONS: Record<string, string> = {
  AB: "Alberta",
  BC: "British Columbia",
  GH: "Golden Horseshoe",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Newfoundland/Labrador",
  NS: "Nova Scotia",
  ONE: "Ontario East",
  ONN: "Ontario North",
  ONS: "Ontario South",
  PE: "Prince Edward Island",
  QC: "Quebec",
  SK: "Saskatchewan",
  TER: "Territories",
}

/// Every valid section: both tables and nothing else. `MX` and `DX` are valid
/// exchanges but are not sections.
export const ALL_SECTIONS: Record<string, string> = { ...ARRL_SECTIONS, ...RAC_SECTIONS }

/// Shorter names for the score panel, where the full name does not fit.
export const ABBREVIATED_SECTION_NAMES: Record<string, string> = {
  AK: "Alaska",
  AL: "Alabama",
  AR: "Arkansas",
  AZ: "Arizona",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  EB: "East Bay",
  EMA: "Eastern Mass.",
  ENY: "Eastern NY",
  EPA: "Eastern Penn.",
  EWA: "Eastern Wash.",
  GA: "Georgia",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  LAX: "Los Angeles",
  MDC: "Maryland & DC",
  ME: "Maine",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NFL: "Northern Florida",
  NH: "New Hampshire",
  NLI: "NYC & Long Is.",
  NM: "New Mexico",
  NNJ: "Northern NJ",
  NNY: "Northern NY",
  NTX: "North Texas",
  NV: "Nevada",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  ORG: "Orange",
  PAC: "Pacific",
  PR: "Puerto Rico",
  RI: "Rhode Is.",
  SB: "Santa Barbara",
  SC: "South Carolina",
  SCV: "Sta. Clara Val.",
  SD: "South Dakota",
  SDG: "San Diego",
  SF: "San Francisco",
  SFL: "Southern FL",
  SJV: "San Joaquin Val.",
  SNJ: "Southern NJ",
  STX: "South Texas",
  SV: "Sacramento Val.",
  TN: "Tennessee",
  UT: "Utah",
  VA: "Virginia",
  VI: "US Virgin Is.",
  VT: "Vermont",
  WCF: "W. Central Florida",
  WI: "Wisconsin",
  WMA: "Western Mass.",
  WNY: "Western NY",
  WPA: "Western Penn.",
  WTX: "West Texas",
  WV: "West Virginia",
  WWA: "Western Wash.",
  WY: "Wyoming",
  AB: "Alberta",
  BC: "British Col.",
  GH: "Golden Horseshoe",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Nfld. & Lab.",
  NS: "Nova Scotia",
  ONE: "Ontario E.",
  ONN: "Ontario N.",
  ONS: "Ontario S.",
  PE: "P.E.I.",
  QC: "Quebec",
  SK: "Saskatchewan",
  TER: "Territories",
}

/// The US call area a section sits in, for ranking a guess: a W1 is far
/// likelier to be in EMA than in SDG.
///
/// NOT `Record<string, number>` — the thirteen Canadian sections carry the
/// STRING 'Canada', having no US call area. Typing it as numbers compiled them
/// into bare identifiers, which only `shared/` joining the typecheck caught.
export const CALL_AREA_FOR_SECTION: Record<string, number | string> = {
  CT: 1,
  EMA: 1,
  ME: 1,
  NH: 1,
  RI: 1,
  VT: 1,
  WMA: 1,
  ENY: 2,
  NNY: 2,
  NLI: 2,
  SNJ: 2,
  NNJ: 2,
  WNY: 2,
  DE: 3,
  MDC: 3,
  EPA: 3,
  WPA: 3,
  AL: 4,
  SFL: 4,
  GA: 4,
  TN: 4,
  KY: 4,
  VA: 4,
  NC: 4,
  WCF: 4,
  NFL: 4,
  PR: 4,
  SC: 4,
  VI: 4,
  AR: 5,
  NTX: 5,
  LA: 5,
  OK: 5,
  MS: 5,
  STX: 5,
  NM: 5,
  WTX: 5,
  EB: 6,
  SDG: 6,
  LAX: 6,
  SF: 6,
  SCV: 6,
  ORG: 6,
  SJV: 6,
  SB: 6,
  SV: 6,
  PAC: 6,
  AK: 7,
  NV: 7,
  AZ: 7,
  OR: 7,
  EWA: 7,
  UT: 7,
  ID: 7,
  WWA: 7,
  MT: 7,
  WY: 7,
  MI: 8,
  OH: 8,
  WV: 8,
  IL: 9,
  WI: 9,
  IN: 9,
  CO: 0,
  MO: 0,
  IA: 0,
  NE: 0,
  KS: 0,
  ND: 0,
  MN: 0,
  SD: 0,
  ONN: "Canada",
  AB: "Canada",
  ONE: "Canada",
  BC: "Canada",
  GH: "Canada",
  MB: "Canada",
  NB: "Canada",
  NL: "Canada",
  NS: "Canada",
  PE: "Canada",
  QC: "Canada",
  SK: "Canada",
  TER: "Canada",
}

/// Callsign prefixes that name their section outright — the territories and
/// possessions, where the prefix IS the answer.
export const PREFIX_TO_LOCATION: Record<string, string> = {
  KH1: "PAC",
  KH2: "PAC",
  KH3: "PAC",
  KH4: "PAC",
  KH5: "PAC",
  KH6: "PAC",
  KH7: "PAC",
  KH8: "PAC",
  KH9: "PAC",
  KL7: "AK",
  KP4: "PR",
  KP2: "VI",
  VE1: "NS",
  VA1: "NS",
  VE2: "QC",
  VA2: "QC",
  VE4: "MB",
  VA4: "MB",
  VE5: "SK",
  VA5: "SK",
  VE6: "AB",
  VA6: "AB",
  VE7: "BC",
  VA7: "BC",
  VE8: "TER",
  VA8: "TER",
  VE9: "NB",
  VA9: "NB",
  VO1: "NL",
  VO2: "NL",
  VY0: "TER",
  VY1: "TER",
  VY2: "PE",
  XE: "MX",
}
